### Get scenes

GET {{base_url}}/scenes
Accept: application/json
x-api-key: {{api_key}}

### Get scene with id

GET {{base_url}}/scenes/{{scene_id}}
Accept: application/json
x-api-key: {{api_key}}

### Create scene

POST {{base_url}}/scenes
Content-Type: application/json
x-api-key: {{api_key}}

{
  "name": "Jane Doe"
}

### Modify scene with id

PUT {{base_url}}/scenes/{{scene_id}}
Content-Type: application/json
x-api-key: {{api_key}}

{
  "name": "Robot Jane"
}

### Delete scene with id

DELETE {{base_url}}/scenes/{{scene_id}}
Accept: application/json
x-api-key: {{api_key}}
