### Get scenes

GET {{base_url}}/scenes
Accept: application/json
x-api-key: {{api_key}}

### Get scene with id

@get_id = 74796a95-48cf-49da-869f-547982c1c0f2
GET {{base_url}}/scenes/{{get_id}}
Accept: application/json
x-api-key: {{api_key}}

### Create scene

POST {{base_url}}/scenes
Content-Type: application/json
x-api-key: {{api_key}}

{
  "name": "Jane Doe"
}

### Modify scene with id

@put_id = 191561f7-fbd2-45e8-87f4-b21f55a0658f
PUT {{base_url}}/scenes/{{put_id}}
Content-Type: application/json
x-api-key: {{api_key}}

{
  "name": "Robot Jane"
}

### Delete scene with id

@delete_id = 191561f7-fbd2-45e8-87f4-b21f55a0658f
DELETE {{base_url}}/scenes/{{delete_id}}
Accept: application/json
x-api-key: {{api_key}}
